name: domain_driven_design_note_app
description: a Flutter note app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  auto_route: ^7.9.2
  bloc: ^8.1.1
  cloud_firestore: ^4.16.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_gen: ^5.3.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.2.0
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  implicitly_animated_reorderable_list_2: ^0.5.1
  injectable: ^2.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.0
  uuid: ^4.1.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: 'Rubik'
      fonts:
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Light.ttf

flutter_intl:
  enabled: true

flutter_gen:
  output: lib/generated/

  
